# Site settings
title: 新闻200
email: your-email@domain.com
description: 这里有你想知道的新闻。
baseurl: 
url:
copyright: '&copy; 2018 新闻200'
permalink: /article-:year:month:day:hour:minute:second

# Custom theme could be generated at: https://getmdl.io/customize/index.html
material_theme: blue-deep_orange

